name: Generate Snake

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake.svg?color_snake=orange&color_dots=#ebedf0,#bfd6f6,#64a1f4,#4b91f1,#3c7dd0
            dist/github-snake-dark.svg?color_snake=orange&color_dots=#161b22,#0d3b6f,#1e5aa8,#4b91f1,#8dbdff
            dist/github-snake.gif?color_snake=orange&color_dots=#161b22,#0d3b6f,#1e5aa8,#4b91f1,#8dbdff
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: crazy-max/ghaction-github-pages@v4.0.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
